In [199]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split, GridSearchCV

In [171]:
# Load the dataset
df = pd.read_csv('Consulting_survey_DataSet (3).csv')

In [172]:
# Renaming the columns to shorter and easier-to-use names
df.columns = [
    'timestamp',
    'current_consulting_firm',
    'current_firm',
    'current_practice',
    'current_title',
    'current_country',
    'current_compensation_usd',
    'estimated_bonus_usd_2021',
    'expected_total_compensation',
    'weekly_hours',
    'offer_received',
    'offer_from_consulting_firm',
    'highest_offer_firm',
    'offer_practice',
    'offered_title',
    'offer_country',
    'highest_offer_compensation_usd',
    'highest_offer_bonus_usd',
    'accepted_offer'
]


print(df.columns.tolist())

['timestamp', 'current_consulting_firm', 'current_firm', 'current_practice', 'current_title', 'current_country', 'current_compensation_usd', 'estimated_bonus_usd_2021', 'expected_total_compensation', 'weekly_hours', 'offer_received', 'offer_from_consulting_firm', 'highest_offer_firm', 'offer_practice', 'offered_title', 'offer_country', 'highest_offer_compensation_usd', 'highest_offer_bonus_usd', 'accepted_offer']

In [173]:
df.head()

,timestamp,current_consulting_firm,current_firm,current_practice,current_title,current_country,current_compensation_usd,estimated_bonus_usd_2021,expected_total_compensation,weekly_hours,offer_received,offer_from_consulting_firm,highest_offer_firm,offer_practice,offered_title,offer_country,highest_offer_compensation_usd,highest_offer_bonus_usd,accepted_offer
0,9/29/2021 10:35:35,Yes,Other or Boutique,Commercial/non-federal Practice,Consultant/Associate,United States of America,147000.0,17000.0,164000.0,50-59,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,9/29/2021 10:35:44,Yes,McKinsey,Commercial/non-federal Practice,Senior Manager,Malaysia,142000.0,50000.0,192000.0,60-69,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,9/29/2021 10:36:00,Yes,Deloitte,Commercial/non-federal Practice,Senior Consultant/Senior Associate,United States of America,150000.0,30000.0,180000.0,40-49,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,9/29/2021 10:36:16,Yes,Deloitte,Federal/government Practice,Senior Consultant/Senior Associate,United States of America,95000.0,10000.0,105000.0,40-49,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,9/29/2021 10:36:19,Yes,Kearney,Commercial/non-federal Practice,Consultant/Associate,United States of America,165000.0,32000.0,197000.0,70-79,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [174]:
#Filter with only ppl receiving an offer
df = df[df['offer_received'] == 'Yes']

In [175]:
df

,timestamp,current_consulting_firm,current_firm,current_practice,current_title,current_country,current_compensation_usd,estimated_bonus_usd_2021,expected_total_compensation,weekly_hours,offer_received,offer_from_consulting_firm,highest_offer_firm,offer_practice,offered_title,offer_country,highest_offer_compensation_usd,highest_offer_bonus_usd,accepted_offer
6,9/29/2021 10:36:54,No,NaN,NaN,NaN,Hong Kong,120000.0,18000.0,138000.0,50-59,Yes,No (Industry or other type of non-consulting c...,NaN,NaN,NaN,Hong Kong,120000.0,20000.0,No
7,9/29/2021 10:37:12,Yes,PwC,Federal/government Practice,Senior Consultant/Senior Associate,Australia,75000.0,850.0,75850.0,<40,Yes,Yes,Protiviti,Federal/government Practice,Senior Consultant/Senior Associate,Australia,80000.0,850.0,No
8,9/29/2021 10:37:20,Yes,Other or Boutique,Not Applicable or Don't Know,Consultant/Associate,United States of America,85000.0,12000.0,97000.0,40-49,Yes,Yes,Other or Boutique,Not Applicable or Don't Know,Senior Consultant/Senior Associate,United States of America,110000.0,16000.0,Yes
12,9/29/2021 10:39:11,Yes,Deloitte,Commercial/non-federal Practice,Manager,Canada,110000.0,5500.0,115500.0,60-69,Yes,Yes,Deloitte,Commercial/non-federal Practice,Manager,Canada,110000.0,5500.0,No
13,9/29/2021 10:39:19,Yes,West Monroe,Commercial/non-federal Practice,Senior Consultant/Senior Associate,United States of America,110000.0,7000.0,117000.0,50-59,Yes,No (Industry or other type of non-consulting c...,NaN,NaN,NaN,United States of America,125000.0,10000.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4180,10/17/2021 13:42:32,Yes,BCG,Commercial/non-federal Practice,Consultant/Associate,India,70000.0,15000.0,85000.0,70-79,Yes,No (Industry or other type of non-consulting c...,NaN,NaN,NaN,India,80000.0,16000.0,Thinking about it
4185,10/18/2021 14:56:32,Yes,KPMG,Commercial/non-federal Practice,Senior Manager,United States of America,275000.0,50000.0,325000.0,50-59,Yes,Yes,KPMG,Commercial/non-federal Practice,Senior Manager,United States of America,285000.0,50000.0,Yes
4188,10/18/2021 21:19:56,Yes,KPMG,Commercial/non-federal Practice,Consultant/Associate,United States of America,72000.0,4000.0,76000.0,40-49,Yes,Yes,Guidehouse/Navigant,Commercial/non-federal Practice,Consultant/Associate,United States of America,75000.0,5000.0,No
4191,10/19/2021 0:35:22,Yes,Other or Boutique,Federal/government Practice,Analyst,United States of America,80000.0,6400.0,86400.0,40-49,Yes,Yes,Other or Boutique,Commercial/non-federal Practice,Consultant/Associate,United States of America,92000.0,12000.0,No
4193,10/19/2021 2:05:39,Yes,McKinsey,Not Applicable or Don't Know,Senior Manager,United Kingdom,160000.0,40000.0,200000.0,50-59,Yes,No (Industry or other type of non-consulting c...,NaN,NaN,NaN,United Arab Emirates,250000.0,50000.0,Thinking about it

In [176]:
df = df.drop('timestamp', axis=1)

In [177]:
df

,current_consulting_firm,current_firm,current_practice,current_title,current_country,current_compensation_usd,estimated_bonus_usd_2021,expected_total_compensation,weekly_hours,offer_received,offer_from_consulting_firm,highest_offer_firm,offer_practice,offered_title,offer_country,highest_offer_compensation_usd,highest_offer_bonus_usd,accepted_offer
6,No,NaN,NaN,NaN,Hong Kong,120000.0,18000.0,138000.0,50-59,Yes,No (Industry or other type of non-consulting c...,NaN,NaN,NaN,Hong Kong,120000.0,20000.0,No
7,Yes,PwC,Federal/government Practice,Senior Consultant/Senior Associate,Australia,75000.0,850.0,75850.0,<40,Yes,Yes,Protiviti,Federal/government Practice,Senior Consultant/Senior Associate,Australia,80000.0,850.0,No
8,Yes,Other or Boutique,Not Applicable or Don't Know,Consultant/Associate,United States of America,85000.0,12000.0,97000.0,40-49,Yes,Yes,Other or Boutique,Not Applicable or Don't Know,Senior Consultant/Senior Associate,United States of America,110000.0,16000.0,Yes
12,Yes,Deloitte,Commercial/non-federal Practice,Manager,Canada,110000.0,5500.0,115500.0,60-69,Yes,Yes,Deloitte,Commercial/non-federal Practice,Manager,Canada,110000.0,5500.0,No
13,Yes,West Monroe,Commercial/non-federal Practice,Senior Consultant/Senior Associate,United States of America,110000.0,7000.0,117000.0,50-59,Yes,No (Industry or other type of non-consulting c...,NaN,NaN,NaN,United States of America,125000.0,10000.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4180,Yes,BCG,Commercial/non-federal Practice,Consultant/Associate,India,70000.0,15000.0,85000.0,70-79,Yes,No (Industry or other type of non-consulting c...,NaN,NaN,NaN,India,80000.0,16000.0,Thinking about it
4185,Yes,KPMG,Commercial/non-federal Practice,Senior Manager,United States of America,275000.0,50000.0,325000.0,50-59,Yes,Yes,KPMG,Commercial/non-federal Practice,Senior Manager,United States of America,285000.0,50000.0,Yes
4188,Yes,KPMG,Commercial/non-federal Practice,Consultant/Associate,United States of America,72000.0,4000.0,76000.0,40-49,Yes,Yes,Guidehouse/Navigant,Commercial/non-federal Practice,Consultant/Associate,United States of America,75000.0,5000.0,No
4191,Yes,Other or Boutique,Federal/government Practice,Analyst,United States of America,80000.0,6400.0,86400.0,40-49,Yes,Yes,Other or Boutique,Commercial/non-federal Practice,Consultant/Associate,United States of America,92000.0,12000.0,No
4193,Yes,McKinsey,Not Applicable or Don't Know,Senior Manager,United Kingdom,160000.0,40000.0,200000.0,50-59,Yes,No (Industry or other type of non-consulting c...,NaN,NaN,NaN,United Arab Emirates,250000.0,50000.0,Thinking about it

In [178]:
# Convert "offer_received" to binary (1 if "Yes", else 0)
df['offer_received_binary'] = df['offer_received'].apply(lambda x: 1 if x == 'Yes' else 0)

In [179]:
# Convert "offer_received" to binary (1 if "Yes", else 0)
df['accepted_offer_binary'] = df['accepted_offer'].apply(lambda x: 1 if x == 'Yes' else 0)

In [180]:
# Convert "offer_received" to binary (1 if "Yes", else 0)
df['current_consulting_firm_binary'] = df['current_consulting_firm'].apply(lambda x: 1 if x == 'Yes' else 0)

In [181]:
df = df.drop('offer_received', axis=1)

In [182]:
df = df.drop('accepted_offer', axis=1)

In [183]:
df = df.drop('current_consulting_firm', axis=1)

In [184]:
# Helper function to convert hour ranges to numeric averages
def hours_to_numeric(hours_str):
    if isinstance(hours_str, str) and '-' in hours_str:
        low, high = map(int, hours_str.split('-'))
        return (low + high) / 2
    return 0  # Use 0 or NaN if the format is unexpected

df['weekly_hours_numeric'] = df['weekly_hours'].apply(hours_to_numeric)

In [185]:
df = df.drop('weekly_hours', axis=1)

In [186]:
offer_counts = df['offer_from_consulting_firm'].value_counts()

print(offer_counts)

offer_from_consulting_firm
Yes                                                      625
No (Industry or other type of non-consulting company)    487
Name: count, dtype: int64

In [187]:
# Convert "offer_received" to binary (1 if "Yes", else 0)
df['offer_from_consulting_firm'] = df['offer_from_consulting_firm'].apply(lambda x: 1 if x == 'Yes' else 0)

In [188]:
df.head()

,current_firm,current_practice,current_title,current_country,current_compensation_usd,estimated_bonus_usd_2021,expected_total_compensation,offer_from_consulting_firm,highest_offer_firm,offer_practice,offered_title,offer_country,highest_offer_compensation_usd,highest_offer_bonus_usd,offer_received_binary,accepted_offer_binary,current_consulting_firm_binary,weekly_hours_numeric
6,NaN,NaN,NaN,Hong Kong,120000.0,18000.0,138000.0,0,NaN,NaN,NaN,Hong Kong,120000.0,20000.0,1,0,0,54.5
7,PwC,Federal/government Practice,Senior Consultant/Senior Associate,Australia,75000.0,850.0,75850.0,1,Protiviti,Federal/government Practice,Senior Consultant/Senior Associate,Australia,80000.0,850.0,1,0,1,0.0
8,Other or Boutique,Not Applicable or Don't Know,Consultant/Associate,United States of America,85000.0,12000.0,97000.0,1,Other or Boutique,Not Applicable or Don't Know,Senior Consultant/Senior Associate,United States of America,110000.0,16000.0,1,1,1,44.5
12,Deloitte,Commercial/non-federal Practice,Manager,Canada,110000.0,5500.0,115500.0,1,Deloitte,Commercial/non-federal Practice,Manager,Canada,110000.0,5500.0,1,0,1,64.5
13,West Monroe,Commercial/non-federal Practice,Senior Consultant/Senior Associate,United States of America,110000.0,7000.0,117000.0,0,NaN,NaN,NaN,United States of America,125000.0,10000.0,1,0,1,54.5

In [189]:
# Identify object-type columns
object_columns = df.select_dtypes(include=['object']).columns

# Review object columns and decide how to handle each
print("Object columns:", object_columns)

Object columns: Index(['current_firm', 'current_practice', 'current_title', 'current_country',
       'highest_offer_firm', 'offer_practice', 'offered_title',
       'offer_country'],
      dtype='object')

In [190]:
categorical_columns = [
    'current_firm',
    'current_practice',
    'current_title',
    'current_country',
    'offer_from_consulting_firm',
    'highest_offer_firm',
    'offer_practice',
    'offered_title',
    'offer_country',
]

# One-Hot Encoding for nominal categories
df = pd.get_dummies(df, columns=categorical_columns, drop_first=True)

# Label Encoding for binary columns or ordinal categories if any
# Example for binary (yes/no) - adjust based on actual data
if 'offer_received' in df.columns:
    df['offer_received'] = df['offer_received'].apply(lambda x: 1 if x == 'Yes' else 0)

# Optional: Handle numerical columns if needed (for example, compensation might need scaling later)
numerical_columns = ['current_compensation_usd', 'estimated_bonus_usd_2021',
                     'expected_total_compensation', 'weekly_hours_numeric',
                     'highest_offer_compensation_usd', 'highest_offer_bonus_usd',]

# Check for missing values and handle them
df[numerical_columns] = df[numerical_columns].fillna(df[numerical_columns].median())  # Fill missing numerical data with median

# The dataset is now ready for modeling
print("Processed DataFrame ready for model training:", df.head())

Processed DataFrame ready for model training:     current_compensation_usd  estimated_bonus_usd_2021  \
6                   120000.0                   18000.0
7                    75000.0                     850.0
8                    85000.0                   12000.0
12                  110000.0                    5500.0
13                  110000.0                    7000.0

    expected_total_compensation  highest_offer_compensation_usd  \
6                      138000.0                        120000.0
7                       75850.0                         80000.0
8                       97000.0                        110000.0
12                     115500.0                        110000.0
13                     117000.0                        125000.0

    highest_offer_bonus_usd  offer_received_binary  accepted_offer_binary  \
6                   20000.0                      1                      0
7                     850.0                      1                      0
8                   16000.0                      1                      1
12                   5500.0                      1                      0
13                  10000.0                      1                      0

    current_consulting_firm_binary  weekly_hours_numeric  \
6                                0                  54.5
7                                1                   0.0
8                                1                  44.5
12                               1                  64.5
13                               1                  54.5

    current_firm_Alvarez & Marsal  ...  offer_country_Sweden  \
6                           False  ...                 False
7                           False  ...                 False
8                           False  ...                 False
12                          False  ...                 False
13                          False  ...                 False

    offer_country_Switzerland  offer_country_Taiwan  offer_country_Thailand  \
6                       False                 False                   False
7                       False                 False                   False
8                       False                 False                   False
12                      False                 False                   False
13                      False                 False                   False

    offer_country_The Republic of South Korea  offer_country_Turkey  \
6                                       False                 False
7                                       False                 False
8                                       False                 False
12                                      False                 False
13                                      False                 False

    offer_country_Ukraine  offer_country_United Arab Emirates  \
6                   False                               False
7                   False                               False
8                   False                               False
12                  False                               False
13                  False                               False

    offer_country_United Kingdom  offer_country_United States of America
6                          False                                   False
7                          False                                   False
8                          False                                    True
12                         False                                   False
13                         False                                    True

[5 rows x 213 columns]

In [192]:
X = df.drop('accepted_offer_binary', axis=1)  # Replace 'target_column' with your actual target column name
y = df['accepted_offer_binary']  # Replace with your target column

In [193]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [194]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [195]:
svc = SVC(kernel='linear')
svc.fit(X_train, y_train)

SVC(kernel='linear')

In [196]:
y_pred = svc.predict(X_test)

In [197]:
# Confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[150   7]
 [ 61   5]]

Classification Report:
              precision    recall  f1-score   support

           0       0.71      0.96      0.82       157
           1       0.42      0.08      0.13        66

    accuracy                           0.70       223
   macro avg       0.56      0.52      0.47       223
weighted avg       0.62      0.70      0.61       223

In [200]:
# Hyperparameter tuning with GridSearchCV
param_grid = {
    'C': [0.1, 1, 10, 100],  # Regularization strength
    'class_weight': [None, 'balanced']
}

grid_search = GridSearchCV(SVC(kernel='linear'), param_grid, cv=5, scoring='f1', verbose=1)
grid_search.fit(X_train, y_train)

# Best parameters and performance
print("Best Parameters:", grid_search.best_params_)

# Evaluate the best model
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Fitting 5 folds for each of 8 candidates, totalling 40 fits
Best Parameters: {'C': 1, 'class_weight': 'balanced'}

Confusion Matrix:
[[103  54]
 [ 22  44]]

Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.66      0.73       157
           1       0.45      0.67      0.54        66

    accuracy                           0.66       223
   macro avg       0.64      0.66      0.63       223
weighted avg       0.71      0.66      0.67       223